# ################################
# # Site Settings
# ################################
# title       : Shining Lite
# description : Your awesome site
# author      : Léonore
# email       : leonoreshaw@gmail.com


################################
# Theme Settings
################################
theme: jekyll-theme-minimal
# permalink   : /:title/


# # Navigation Menus
# header_navigation:
#   - title: Documentation
#     url: /docs/

#   - title: Themes
#     url: https://desiredpersona.com/themes/

#   - title: About
#     url: /about/

#   - title: Blog
#     url: /archive/

#   - title: Contact
#     url: mailto:you@example.com

# footer_navigation:
#   - title: privacy
#     url: /privacy/

#   - title: terms
#     url: /terms/
